name: Build and Deploy to Packagecloud
on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'debian/changelog'
jobs:
  check_version:
    name: Check py & deb pkg versions match
    uses: WLAN-Pi/gh-workflows/.github/workflows/check-py-deb-pkg-versions-match.yml@main
    with:
      python_version_file_path: 'ctx/__init__.py'
  format:
    name: Get formatted version for filename
    uses: WLAN-Pi/gh-workflows/.github/workflows/get-formatted-version-string.yml@main
  sbuild_deploy:
    name: sbuild deploy pkg
    needs: 
      - format
    uses: WLAN-Pi/gh-workflows/.github/workflows/sbuild-deploy-pkg.yml@main
    with:
      pkg: wlanpi-ctx
      version: ${{ needs.format.outputs.version }} 
    secrets: inherit
  slack-workflow-status:
    if: ${{ always() && (! github.event.pull_request.head.repo.fork) }}
    name: Post workflow status to Slack
    needs:
      - sbuild_deploy
    runs-on: "${{ vars.RUNS_ON || 'ubuntu-22.04' }}"
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}